exception Bad_construction of string;;
exception Incompatible_outputs;;
exception Multiple_definition of string;;
exception Undefined of string;;
exception Incompatible_definitions of string;;
exception Type_mismatch of string;;
exception Invalide_argument_numbers of string;;
exception Incompatible_direction of string;;
exception Incorrect_call of string;;
exception Clock_Error of string;;